### ISSUE TITLE
Please add pause option

### ISSUE THREAD

**Issue by vshevch** [carsonip/alexa-pocket#12]
Can you please add an option to pause the reading of an article. Sometimes I want to pause for a bit, but whenever I ask Alexa to pause, it just goes back to the beginning.
Also, if there is a way to resume from where you left off, or an ability to fast forward to a certain point (ex. Alexa skip 10 seconds), that would be awesome. Though I understand if that is technologically impossible.

**Comment by carsonip** [comment]
Sorry for the late reply. I'm afraid it is not technically possible to pause / skip now. Please correct me if I'm wrong. Close for now.
