### ISSUE TITLE
Make skill available in India

### ISSUE THREAD

**Issue by kiranmr** [carsonip/alexa-pocket#4]
Firstly, thanks for implementing this extremely useful skill.
This is not yet available for India region. Alexa and echo devices were launched in India about a month ago.
There is blog on adding India region to skills https://developer.amazon.com/blogs/alexa/post/f89ae457-9538-4b57-b3f6-dbef2f600412/how-to-update-your-skills-for-india

It will be great if skill is made available for India region.

**Comment by carsonip** [comment]
Hi Kiran, thanks for supporting this skill! I suppose as long as it is in English, I can make it happen. Actually UK should be available as well. The only hurdle now is that in the latest version (which is not published) the search tag function requires AMAZON.LITERAL but it is not supported in any other languages other than English (US). Maybe I'll remove that function first and think about it later.
Let's see if I have time to do this during the holidays.

**Comment by carsonip** [comment]
Hi, sorry for the delay. I have submitted for certification just now. Hopefully it will go live in India in a few days.

**Comment by kiranmr** [comment]
Thanks a lot Carson

**Comment by carsonip** [comment]
@kiranmr It should be live now. Please check.

**Comment by kiranmr** [comment]
@carsonip yes , the skill is available in India. It works great. Thanks once again.
