### ISSUE TITLE
reading articles doesn't work well

### ISSUE THREAD

**Issue by robingoren** [carsonip/alexa-pocket#5]
I just did a test. I added 4 NY Times articles to My Pocket. When it opens it says i have 4 articles, and lists them all.  When I go to read 1 it works - but if i go go "next" or say "read #2" it says no other articles after reading the 1st one!

Also, if i have numerous articles (i.e. more than 10) i won't be able to remember which was is which number - would be nice if it just started by reading the headlines, and if you didn't have to mention an article number - better if you could just say "alexa read" when a headline is read to you - then say "alexa next" either in the middle or end of that article to be able to go from article to article all in a row but not be required to listen to each fully.  Let me know if these are possibities - otherwise I won't be able to use this skill. Thanks.

**Comment by carsonip** [comment]
Thanks for the comment. Really appreciate it.
The 1st one is more of a storage issue. I think that's the side effect of the workaround. I will fix that.
The 2nd is a good feature request. Will implement.
I'm away from keyboard now. Hopefully can fix these next week.

**Comment by carsonip** [comment]
The function of reading the next article after finishing one is added in https://github.com/carsonip/alexa-pocket/commit/d81238e2e1c312342dbda19b4bac84c605cb0aba. The new version of the skill will be deployed as soon as the corresponding German translations are ready.

**Comment by mrwhoruhe** [comment]
Reading articles with this skill is great, except that it asks (I think every 2 mins) if it should continue. It would be preferable to just let Alexa read the entire article or using a command like "Alexa read next article" to do just that! Or "Alexa read #2" etc. 

I have to say that regardless this is a really helpful skill! Thank you for taking the time to create it.

**Comment by carsonip** [comment]
Hi @mrwhoruhe, thanks for leaving a comment. I would love to have it read the entire article but this is a limitation imposed by Alexa (i.e. a limitation of the length / size of the response). Therefore, the skill cannot work without this workaround.

**Comment by carsonip** [comment]
I'll close this issue with a reference to the documentation on Alexa response limitations: https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html#response-format
