### ISSUE TITLE
Enable the skill for new regions like India

### ISSUE THREAD

**Issue by xdev2381** [carsonip/alexa-pocket#8]
Please enable your skill for new Alexa regions like India. I am unable to enable the skill in India.
this is the error message in the amazon.com site.
You are not eligible to enable this skill due to geographical restrictions.

**Comment by carsonip** [comment]
Hi @xdev2381 , I am working on it already. I have submitted for certification for a few times and have already fixed the bugs. I am confident that the skill will pass certification in this week and will be available to users from India, Germany, etc. Thanks for your support!

**Comment by carsonip** [comment]
The certification isn't going well. It is now stuck at some non-technical issues with the German skill. If the certification fails again, maybe I'll temporarily cancel German and let India and other regions pass first. Sorry to keep you waiting.

**Comment by carsonip** [comment]
@xdev2381 It should be live now. Please check.

**Comment by xdev2381** [comment]
I am still unable to install. I tried from amazon.in, amazon.com and also alexa.amazon.in. Please see the screenshots.Is there some other way I can find the skill and enable it? I tried enabling it using voice on alexa also.

![alexa-amazion-in](https://user-images.githubusercontent.com/15164995/37464654-0582731e-287f-11e8-8909-e7e5d8a194e2.png)
![amazon-com](https://user-images.githubusercontent.com/15164995/37464656-05b1dabe-287f-11e8-8ed9-b290e3b26b65.png)
![amazon-in](https://user-images.githubusercontent.com/15164995/37464657-05e0bc58-287f-11e8-95ea-98acb98785b8.png)

**Comment by carsonip** [comment]
Whoops, the name of the skill is "My Pocket". Please let me know if it works for you.

**Comment by carsonip** [comment]
@xdev2381 Here's the skill in case you need it. https://www.amazon.com/My-Pocket-Unofficial-Skill/dp/B071KZFKLM

**Comment by xdev2381** [comment]
No, Still no luck. A search of "My Pocket" does not give any results in alexa.amazon.in or amazon.in. In amazon.com It displays the same message. "You are not eligible to enable this skill due to geographical restrictions.".

**Comment by carsonip** [comment]
This is weird. In my developer console it says "Language: English (IN), English (AU), German, English (US), English (CA), English (UK)". Let me contact Amazon for help.

**Comment by carsonip** [comment]
Reply from Amazon Developer Support:
> Hi,
>
> Thank you for your patience while we worked on reviewing your "My Pocket: Unofficial Pocket Skill" skill content. It should now be live in the other regions you were having difficulty finding them. Some countries in which we publish skills may have more restrictive standards for what qualifies as offensive or non-compliant content which is why it contains a mature rating.

I have tried searching for it in amazon.in and now it works. Thanks for reporting the issue.
